using System;
using System.Collections.Generic;
using System.Linq;


namespace Sylabizator
{
    static class Syllabizer
    {
        private readonly static char[] vowels = { 'a', 'e', 'i', 'o', 'u', 'ó', 'y', 'ą', 'ę' };
        private readonly static char[] consonants = { 'b', 'c', 'ć', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'ł', 'm', 'n', 'ń', 'p', 'r', 's', 'ś', 't', 'w', 'z', 'ź', 'ż', 'x', 'q', 'v' };

        private readonly static string[] prefixes =
            {"zrosło",
            "zoo",
            "znie",
            "zmienno",
            "zmartwych",
            "złocisto",
            "zimo",
            "zimno",
            "ziemisto",
            "zielono",
            "zielonkawo",
            "zielonawo",
            "ze",
            "zasado",
            "zachodnio",
            "za",
            "wy",
            "wszech",
            "współ",
            "wschodnio",
            "wrębo",
            "wpół",
            "wolto",
            "wolno",
            "wokół",
            "wokoło",
            "wodoro",
            "wodo",
            "wodno",
            "wobulo",
            "wniebo",
            "włoso",
            "wiscero",
            "wiruso",
            "wiro",
            "wino",
            "wierszo",
            "wielo",
            "wielko",
            "wideo",
            "wice",
            "węglo",
            "wez",
            "wewnątrz",
            "wes",
            "wenero",
            "wczesno",
            "wato",
            "wapnio",
            "wanado",
            "utero",
            "ustrojo",
            "uro",
            "urano",
            "uni",
            "undecy",
            "ultra",
            "u",
            "tytano",
            "tysiąc",
            "twardo",
            "turbo",
            "trzystu",
            "trzynasto",
            "trzecio",
            "trybo",
            "tryba",
            "try",
            "trój",
            "tropo",
            "trombo",
            "triskaideka",
            "tris",
            "tri",
            "traumato",
            "trans",
            "tragi",
            "tracheo",
            "towaro",
            "torfo",
            "torako",
            "topo",
            "top",
            "tono",
            "toksyko",
            "tokso",
            "toko",
            "tleno",
            "tio",
            "tetra",
            "teslo",
            "tero",
            "termo",
            "terato",
            "tera",
            "teo",
            "telluro",
            "tele",
            "techno",
            "teatro",
            "tauto",
            "tau",
            "tao",
            "tangenso",
            "tanato",
            "talaso",
            "takso",
            "tachysto",
            "tachy",
            "tacho",
            "tachisto",
            "tacheo",
            "święto",
            "świato",
            "światło",
            "środkowo",
            "średnio",
            "szybko",
            "sztorm",
            "szkarłatno",
            "sześćset",
            "sześćdziesięcio",
            "sześć",
            "sześcio",
            "szesnasto",
            "szeroko",
            "szczęko",
            "szczero",
            "szarpi",
            "szaro",
            "szarawo",
            "syn",
            "symilo",
            "symfero",
            "syfilido",
            "sydero",
            "surowco",
            "super",
            "sulfo",
            "sucho",
            "sub",
            "styro",
            "stylo",
            "stu",
            "strzało",
            "strobo",
            "strepto",
            "strato",
            "stereo",
            "steno",
            "stegano",
            "staro",
            "stalowo",
            "srebrzysto",
            "srebrno",
            "sprawo",
            "spół",
            "sporo",
            "spermato",
            "speleo",
            "spektro",
            "spec",
            "sono",
            "somato",
            "soft",
            "sodo",
            "socjo",
            "socjal",
            "soc",
            "słono",
            "słodko",
            "słabo",
            "skrzydło",
            "skrzelo",
            "sklero",
            "skio",
            "skia",
            "sinuso",
            "silno",
            "siedmio",
            "siedemset",
            "siedemnasto",
            "siedemdziesięcio",
            "siedem",
            "siarko",
            "sfigmo",
            "sfero",
            "seskwi",
            "sero",
            "serbo",
            "sensyto",
            "semito",
            "semio",
            "semi",
            "seleno",
            "sekundo",
            "seksty",
            "sekso",
            "seks",
            "sejsmo",
            "scyntylo",
            "scynty",
            "schizo",
            "sceno",
            "sapro",
            "samo",
            "ryzo",
            "ryno",
            "ryn",
            "ruso",
            "rtęcio",
            "różowo",
            "roze",
            "rozdzielno",
            "roz",
            "rodo",
            "reumato",
            "reo",
            "rentgeno",
            "rdzenio",
            "rdzawo",
            "radio",
            "pusto",
            "purpurowo",
            "ptero",
            "psychro",
            "psycho",
            "psycha",
            "pseudo",
            "przyrodo",
            "przy",
            "przednio",
            "przed",
            "przeciw",
            "prze",
            "proto",
            "progno",
            "profilo",
            "pro",
            "pre",
            "prawo",
            "prawdo",
            "pra",
            "późno",
            "północno",
            "pół",
            "potaso",
            "post",
            "porno",
            "popularno",
            "popielato",
            "pood",
            "ponad",
            "pomarańczowo",
            "południowo",
            "polono",
            "poli",
            "polaro",
            "pogodo",
            "pode",
            "pod",
            "po",
            "pneumo",
            "pneumato",
            "pływo",
            "pługo",
            "płowo",
            "płodo",
            "płasko",
            "pluwio",
            "pluto",
            "plio",
            "pletyzmo",
            "pleo",
            "plazmo",
            "platynowo",
            "platyno",
            "plasto",
            "plani",
            "plagio",
            "piro",
            "pikto",
            "piko",
            "piętnasto",
            "pięćset",
            "pięćdziesięcio",
            "pięć",
            "pięcio",
            "piezo",
            "pierzasto",
            "pierwszo",
            "pierwo",
            "piasko",
            "piano",
            "petro",
            "peta",
            "pery",
            "perłowo",
            "penta",
            "pełno",
            "pedo",
            "pede",
            "peda",
            "pato",
            "parzysto",
            "paruset",
            "paru",
            "parteno",
            "paradokso",
            "para",
            "państwowo",
            "państwo",
            "panto",
            "pan",
            "palino",
            "palin",
            "paleo",
            "palato",
            "pajdo",
            "ozono",
            "owoco",
            "owo",
            "oto",
            "ośmio",
            "ostro",
            "osteo",
            "osmo",
            "osiemset",
            "osiemnasto",
            "osiemdziesięcio",
            "osiem",
            "oscylo",
            "orto",
            "oro",
            "ornito",
            "organo",
            "or",
            "opty",
            "opto",
            "opinio",
            "oo",
            "onto",
            "onko",
            "omo",
            "ombro",
            "ołowiano",
            "oliwkowo",
            "oligo",
            "oleo",
            "okto",
            "okta",
            "oksy",
            "około",
            "ognio",
            "oftalmo",
            "ofio",
            "odonto",
            "od",
            "ochlo",
            "oceano",
            "obe",
            "obco",
            "ob",
            "o",
            "nykto",
            "nukleo",
            "nozo",
            "nowo",
            "nony",
            "noni",
            "nona",
            "nomo",
            "niutono",
            "nitro",
            "nisko",
            "nie",
            "niby",
            "neuro",
            "neo",
            "nekro",
            "negro",
            "nefro",
            "nefelo",
            "nauto",
            "nauko",
            "narto",
            "narko",
            "naprzemian",
            "nano",
            "naj",
            "nago",
            "nade",
            "nad",
            "na",
            "myrmeko",
            "myko",
            "muzyko",
            "muzeo",
            "multi",
            "muko",
            "mowo",
            "moto",
            "morfo",
            "mono",
            "mnemo",
            "młodo",
            "mizo",
            "mito",
            "miria",
            "miodo",
            "mio",
            "mini",
            "mimo",
            "mili",
            "mikso",
            "mikro",
            "miko",
            "miękko",
            "między",
            "mielo",
            "miedzio",
            "miedziano",
            "midi",
            "męsko",
            "męczy",
            "mezzo",
            "mezo",
            "metro",
            "methemo",
            "meteoro",
            "meteo",
            "metalo",
            "meta",
            "merkuro",
            "melo",
            "melano",
            "megalo",
            "mega",
            "mechano",
            "matowo",
            "materiało",
            "masto",
            "mareo",
            "mano",
            "mangano",
            "mammo",
            "mało",
            "malako",
            "maksi",
            "makro",
            "magnezo",
            "magneto",
            "łąko",
            "łami",
            "luźno",
            "luteo",
            "lumpen",
            "lumeno",
            "ludo",
            "logo",
            "lodo",
            "lito",
            "literaturo",
            "liścio",
            "lipo",
            "lino",
            "limno",
            "limni",
            "limfo",
            "lik",
            "lewo",
            "leuko",
            "lepto",
            "lepido",
            "leksyko",
            "leko",
            "lekko",
            "lato",
            "laryngo",
            "laparo",
            "lantano",
            "lakto",
            "kyno",
            "kwinty",
            "kwiato",
            "kwazi",
            "kwaśno",
            "kwaso",
            "kwadro",
            "kulturo",
            "kulombo",
            "ksylo",
            "kso",
            "księgo",
            "ksero",
            "kseno",
            "krzywo",
            "krzemo",
            "krystalo",
            "krypto",
            "krymino",
            "krwisto",
            "kruczo",
            "krótko",
            "krio",
            "krasno",
            "kranio",
            "kościo",
            "kostno",
            "kostiumo",
            "kosmo",
            "korzenio",
            "kortyko",
            "korono",
            "kopro",
            "kontr",
            "kono",
            "kon",
            "komedio",
            "kom",
            "koło",
            "kokso",
            "kobaltowo",
            "kobalto",
            "ko",
            "kliwer",
            "klepto",
            "klaustro",
            "kino",
            "kineto",
            "kinemato",
            "kimo",
            "kilo",
            "kilkuset",
            "kilkunasto",
            "kilkudziesięcio",
            "kilku",
            "kilko",
            "kero",
            "kerato",
            "keno",
            "każdo",
            "kata",
            "kasztanowo",
            "kasztanowato",
            "karto",
            "karno",
            "kario",
            "kardio",
            "karcyno",
            "karcino",
            "karbo",
            "kapilaro",
            "kapel",
            "kancero",
            "kalory",
            "kalo",
            "kalejdo",
            "kalcy",
            "kako",
            "judeo",
            "jono",
            "jodo",
            "języko",
            "jedyno",
            "jedno",
            "jedenasto",
            "jawno",
            "jasno",
            "jadło",
            "izo",
            "irydo",
            "ir",
            "intro",
            "intra",
            "inter",
            "ino",
            "inno",
            "infra",
            "info",
            "indo",
            "in",
            "impulso",
            "importo",
            "immuno",
            "im",
            "ilu",
            "ilo",
            "ikono",
            "idio",
            "ideo",
            "ichtio",
            "hymno",
            "hydro",
            "hurra",
            "horo",
            "homojo",
            "homo",
            "homeo",
            "holo",
            "hodo",
            "hode",
            "historio",
            "histo",
            "hipso",
            "hipo",
            "hipno",
            "hiper",
            "hilo",
            "higro",
            "hiero",
            "hetero",
            "heral",
            "hera",
            "hepta",
            "hemo",
            "hemio",
            "hemi",
            "hemato",
            "helo",
            "helio",
            "hekto",
            "hekso",
            "heksa",
            "harmono",
            "hard",
            "hapto",
            "haplo",
            "halo",
            "hallo",
            "hali",
            "hagio",
            "gyne",
            "gwaro",
            "grzybo",
            "grzbieto",
            "grunto",
            "grubo",
            "grawi",
            "granulo",
            "graniasto",
            "granatowo",
            "gramo",
            "grafo",
            "górno",
            "gorzko",
            "gorzkawo",
            "gono",
            "goło",
            "glotto",
            "gloso",
            "glipto",
            "glino",
            "gliniasto",
            "gliko",
            "glicero",
            "glebo",
            "gineko",
            "giganto",
            "giga",
            "geronto",
            "germano",
            "geo",
            "gazo",
            "gastro",
            "gamo",
            "galwano",
            "galo",
            "gallo",
            "galakto",
            "gado",
            "ftyzjo",
            "franko",
            "foto",
            "fosforo",
            "fosfo",
            "formalno",
            "fono",
            "folio",
            "fluwio",
            "fluory",
            "fluoro",
            "flekso",
            "fizyko",
            "fizjo",
            "fito",
            "fioletowo",
            "fin",
            "filo",
            "filmo",
            "feto",
            "ferro",
            "feno",
            "femto",
            "felo",
            "feld",
            "farmako",
            "farado",
            "fantazjo",
            "fakto",
            "eury",
            "europo",
            "euro",
            "eu",
            "eto",
            "etno",
            "eroto",
            "ergo",
            "epistolo",
            "epidia",
            "epi",
            "eo",
            "entomo",
            "ento",
            "entero",
            "energo",
            "energio",
            "endo",
            "encefalo",
            "en",
            "empirio",
            "embrio",
            "elektrono",
            "elektro",
            "elasto",
            "ekwi",
            "ekto",
            "ekstra",
            "eksa",
            "eks",
            "ekrano",
            "eko",
            "egzo",
            "echo",
            "ebulio",
            "dźwięko",
            "dziewiętnasto",
            "dziewięćset",
            "dziewięćdziesięcio",
            "dziewięć",
            "dziewięcio",
            "dziesięcio",
            "dyz",
            "dys",
            "dynamo",
            "dwustu",
            "dwunasto",
            "dwudziesto",
            "dwu",
            "dwój",
            "duodecy",
            "drzewo",
            "dromo",
            "drogo",
            "drobno",
            "dolno",
            "dokso",
            "dodeka",
            "do",
            "długo",
            "dłoniasto",
            "diplo",
            "dino",
            "diafano",
            "dia",
            "di",
            "dez",
            "desmo",
            "dermo",
            "dermato",
            "dendro",
            "demono",
            "demo",
            "delmo",
            "deka",
            "defekto",
            "decy",
            "de",
            "dao",
            "daktylo",
            "ćwierć",
            "czwór",
            "czworo",
            "czterystu",
            "cztery",
            "cztero",
            "czternasto",
            "czterdziesto",
            "często",
            "czerwono",
            "czerwonawo",
            "czecho",
            "czaso",
            "czarno",
            "cyto",
            "cysto",
            "cyno",
            "cynko",
            "cyklo",
            "cyjano",
            "cyber",
            "cis",
            "ciężko",
            "ciężaro",
            "ciepło",
            "cienko",
            "ciemno",
            "chryzo",
            "chrono",
            "chromo",
            "chromato",
            "chorobo",
            "choreo",
            "chondro",
            "chloro",
            "chiro",
            "chino",
            "chemo",
            "chemio",
            "charaktero",
            "chalko",
            "cero",
            "centy",
            "centro",
            "ceno",
            "cemento",
            "celulo",
            "ceglasto",
            "cało",
            "całkowito",
            "brunatno",
            "bronto",
            "broncho",
            "bromo",
            "brio",
            "brązowo",
            "brachy",
            "boro",
            "błogo",
            "błękitno",
            "blasto",
            "bizmuto",
            "biuro",
            "bis",
            "bio",
            "biblioteko",
            "biblio",
            "bibli",
            "biało",
            "białko",
            "białawo",
            "beżowo",
            "bez",
            "beta",
            "berylo",
            "benzo",
            "baty",
            "bato",
            "basi",
            "bary",
            "baro",
            "balneo",
            "baldacho",
            "bakterio",
            "azoto",
            "azeo",
            "awizo",
            "awio",
            "auto",
            "audio",
            "atto",
            "atmo",
            "astro",
            "asteno",
            "arytmo",
            "arysto",
            "artro",
            "arterio",
            "arson",
            "arseno",
            "arcy",
            "archi",
            "archeo",
            "arachno",
            "apo",
            "aorto",
            "antybiotyko",
            "anty",
            "antropo",
            "anto",
            "ante",
            "anglo",
            "angio",
            "anemo",
            "andro",
            "an",
            "ampero",
            "ampelo",
            "amino",
            "amfi",
            "ambi",
            "alumino",
            "alto",
            "alo",
            "allo",
            "allanto",
            "alkilo",
            "algo",
            "alfa",
            "al",
            "akwa",
            "aktyno",
            "aktino",
            "akso",
            "akro",
            "akcelero",
            "akanto",
            "ajchmo",
            "agro",
            "agora",
            "after",
            "afro",
            "aero",
            "aeolo",
            "adreso",
            "administracyjno",
            "adenozyno",
            "acylo",
            "achter",
            "achondro",
            "acetylo",
            "abs",
            "abolicjo",
            "aberro",
            "abdomino",
            "ab",
            "a",};

        public static string[] Run(string input)
        {
            input = input.ToLower();
            string[] toDivide = SeparatePrefix(input);

            LinkedList<string> prefix = Divide(toDivide[0]);
            LinkedList<string> word = Divide(toDivide[1]);

            foreach (string s in word)
            {
                prefix.AddLast(s);
            }
            return prefix.ToArray();
        }

        private static string[] SeparatePrefix(string input)
        {
            string[] output = new string[2];

            foreach (string prefix in prefixes)
            {
                if (input.StartsWith(prefix))
                {
                    output[0] = input.Substring(0, prefix.Length);
                    output[1] = input.Substring(prefix.Length);
                    return output;
                }
            }

            output[0] = string.Empty;
            output[1] = input;
            return output;

        }


        public static LinkedList<string> Divide(string input)
        {
            char[] inputChars = input.ToLower().ToCharArray();

            if (inputChars.Length == 0)
            {
                return new LinkedList<string>();
            }

            int[] validVowelsPositions = FindValidVowels(inputChars);
            if (validVowelsPositions.Length < 2)
            {
                LinkedList<string> result = new LinkedList<string>();
                result.AddFirst(new string(inputChars));
                return result;
            }
            int[] repeatetConsonantsPositions = FindRepeatetConsonants(inputChars);

            int[] breakPointsPositions = new int[validVowelsPositions.Length - 1];

            for (int i = 0, j = 0; i < validVowelsPositions.Length - 1; i++) // Sets break points positions
            {
                bool hasRepeatetRepeatetConsonantsPosition = false;
                foreach (int pos in repeatetConsonantsPositions)
                {
                    if (pos > validVowelsPositions[i] && pos < validVowelsPositions[i + 1])
                    {
                        breakPointsPositions[j] = pos;
                        j++;
                        hasRepeatetRepeatetConsonantsPosition = true;
                        break;
                    }
                }

                if (hasRepeatetRepeatetConsonantsPosition) break;

                float breakPoint = (validVowelsPositions[i + 1] + validVowelsPositions[i]) / 2.0f;
                if ((breakPoint - (int)breakPoint) > 0)
                {
                    breakPointsPositions[j] = (int)breakPoint + 1;
                }
                else
                {
                    breakPointsPositions[j] = (int)breakPoint;
                }



                try
                {
                    if (IsDigraph(inputChars[breakPointsPositions[j] - 1], inputChars[breakPointsPositions[j]]))
                    {
                        breakPointsPositions[j]--;
                    }
                }
                catch (IndexOutOfRangeException) { }
                j++;
            }

            LinkedList<string> output = new LinkedList<string>();


            output.AddLast(input.Substring(0, breakPointsPositions[0]));
            for (int i = 0; i < breakPointsPositions.Length - 1; i++)
            {
                output.AddLast(input.Substring(breakPointsPositions[i], breakPointsPositions[i + 1] - breakPointsPositions[i]));
            }

            output.AddLast(input.Substring(breakPointsPositions[breakPointsPositions.Length - 1]));

            return output;
        }

        private static int[] FindValidVowels(char[] input)
        {
            LinkedList<int> validVowelsPositions = new LinkedList<int>();

            for (int i = 0; i < input.Length - 1; i++)
            {
                if (vowels.Contains(input[i]) && CheckIfVowelIsValid(input[i], input[i + 1]))
                {
                    validVowelsPositions.AddLast(i);
                }
            }
            if (vowels.Contains(input[input.Length - 1]))
            {
                validVowelsPositions.AddLast(input.Length - 1);
            }

            return validVowelsPositions.ToArray();
        }

        private static bool CheckIfVowelIsValid(char vowel, char nextChar)
        {
            if (vowel == 'i' && vowels.Contains(nextChar))
            {
                return false;
            }
            if ((vowel == 'a' || vowel == 'e') && nextChar == 'u')
            {
                return false;
            }
            return true;
        }

        private static int[] FindRepeatetConsonants(char[] input)
        {
            LinkedList<int> RepeatetConsonatsPositions = new LinkedList<int>();
            for (int i = 0; i < input.Length - 1; i++)
            {
                if (input[i] == input[i + 1] && consonants.Contains(input[i]))
                {
                    RepeatetConsonatsPositions.AddLast(i + 1);
                }
            }

            return RepeatetConsonatsPositions.ToArray();
        }

        private static bool IsDigraph(char character, char nextCharacter)
        {
            if ((nextCharacter == 'z') && (character == 'r' || character == 's' || character == 'c' || character == 'd'))
            {
                return true;
            }
            if (character == 'c' && nextCharacter == 'h')
            {
                return true;
            }
            if ((character == 'd') && (nextCharacter == 'ż' || nextCharacter == 'ź'))
            {
                return true;
            }
            return false;
        }
    }
}
